"""Constants for Family Calendar."""

from logging import Logger, getLogger

LOGGER: Logger = getLogger(__package__)

DOMAIN = "kdev_family_calendar"

CONF_CALENDARS = "calendars"
CONF_CALENDAR_SETTINGS = "calendar_settings"
CONF_CALENDAR_NAME = "calendar_name"
CONF_CALENDAR_COLOR = "calendar_color"
CONF_CALENDAR_TEXT_COLOR = "calendar_text_color"
CONF_DAY_MARKERS = "day_markers"
CONF_ICON_KEYWORDS = "icon_keywords"
CONF_VIEW = "view"
CONF_LAYOUT = "layout"
CONF_START_HOUR = "start_hour"
CONF_END_HOUR = "end_hour"
CONF_HOUR_HEIGHT = "hour_height"
CONF_THEME = "theme"
CONF_LIGHT_DAY_COLOR = "light_day_color"
CONF_LIGHT_TODAY_COLOR = "light_today_color"
CONF_LIGHT_CARD_COLOR = "light_card_color"
CONF_DARK_DAY_COLOR = "dark_day_color"
CONF_DARK_TODAY_COLOR = "dark_today_color"
CONF_DARK_CARD_COLOR = "dark_card_color"

DEFAULT_VIEW = "week"
DEFAULT_LAYOUT = "condensed"
DEFAULT_START_HOUR = 7
DEFAULT_END_HOUR = 19
DEFAULT_HOUR_HEIGHT = 48
DEFAULT_THEME = "system"
DEFAULT_CALENDAR_TEXT_COLOR = "#000000"
DEFAULT_CALENDAR_COLORS = ("#eda6b5", "#309bbf", "#d57ff0", "#aaaaaa")
DEFAULT_LIGHT_DAY_COLOR = "#e8e6e0"
DEFAULT_LIGHT_TODAY_COLOR = "#fff3cd"
DEFAULT_LIGHT_CARD_COLOR = "#f0f0f0"
DEFAULT_DARK_DAY_COLOR = "#2a2a2c"
DEFAULT_DARK_TODAY_COLOR = "#3d3419"
DEFAULT_DARK_CARD_COLOR = "#1e1e1e"

DEFAULT_SETTINGS = {
    CONF_VIEW: DEFAULT_VIEW,
    CONF_LAYOUT: DEFAULT_LAYOUT,
    CONF_START_HOUR: DEFAULT_START_HOUR,
    CONF_END_HOUR: DEFAULT_END_HOUR,
    CONF_HOUR_HEIGHT: DEFAULT_HOUR_HEIGHT,
    CONF_THEME: DEFAULT_THEME,
    CONF_LIGHT_DAY_COLOR: DEFAULT_LIGHT_DAY_COLOR,
    CONF_LIGHT_TODAY_COLOR: DEFAULT_LIGHT_TODAY_COLOR,
    CONF_LIGHT_CARD_COLOR: DEFAULT_LIGHT_CARD_COLOR,
    CONF_DARK_DAY_COLOR: DEFAULT_DARK_DAY_COLOR,
    CONF_DARK_TODAY_COLOR: DEFAULT_DARK_TODAY_COLOR,
    CONF_DARK_CARD_COLOR: DEFAULT_DARK_CARD_COLOR,
}
